### PR TITLE
README: remove a note about regular releases

### PR DESCRIPTION
**Pull request by strohel**
Just testing if pushes directly to `main` are allowed (for pushing the version bump for release), this is hopefully uncontroversial enough that it can stay if it gets through.

Okay these are not allowed, so I'm submitting as a PR now I've made the change. :)

## Changelog
None

### CODE REVIEW

**Review by Y-Nak — APPROVED** [review]
👍 

Yeah, the current branch protection setting is quite strict. But I'd like to keep it as is if there is no strong opinion so that I don't make stupid mistakes (I'm not confident in what I do when I feel sleepy).

**Comment by strohel** [comment]
I like the protection rules, they make good sense.

I was just considering that it feels weird to publish i.e. 0.1.9 to creates i.o. and only afterwards merge a PR that updates the version in `Cargo.toml`s to `main`. But I can as well file such a PR before doing any other steps of the release.

**Comment by Y-Nak** [comment]
But it's weird, I guess you can have permission to do so.

**Comment by Y-Nak** [comment]
Do you have permission to merge PR right?

**Comment by strohel** [comment]
> Do you have permission to merge PR right?

Let me check that with #161 (please postpone approving for a bit).

**Comment by Y-Nak** [comment]
`Require status checks to pass before merging` is checked in the current setting, but `Require a pull request before merging` is not checked. Hmm,  it seems the former one works as a stricter rule than the latter one. But I'm not sure 🤷

**Comment by strohel** [comment]
> `Require status checks to pass before merging` is checked in the current setting

Yeah I've tried pushing `readme-remove-release-cycle-info` just as a branch without opening a PR to run the status checks. We in `.github/workflows/ci.yml` we've currently configured to run checks on for `main` on `push`, so they haven't run.

**Comment by strohel** [comment]
> > Do you have permission to merge PR right?
> 
> Let me check that with #161 (please postpone approving for a bit).

Yep I can merge it without any review. :+1:

**Comment by Y-Nak** [comment]
Ok, cool.
Maybe `Require status checks to pass before merging` is the reason why you can't push the change to the main directly.

**Comment by strohel** [comment]
> Maybe `Require status checks to pass before merging` is the reason why you can't push the change to the main directly.

Yeah. Maybe it could be made to work by running the CI checks on all branches, but then that's basically equivalent to opening (and self-merging) a PR. Advantage of a PR (even if insta-merged) is better visibility for other team members, and a place to do post-mortem review.

**Pull request merged**
